[project]
name = "futureagi-mcp-server"
version = "0.1.0"
description = "FutureAGI MCP Server"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "futureagi>=0.5.7",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.2",
]


